services:
  citus_coordinator:
    env_file:
      - .env
    image: citusdata/citus:13.0.1
    container_name: citus_coordinator
    hostname: citus-coordinator
    ports:
      - "${COORDINATOR_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      WORKER1_HOST: citus_worker1
      WORKER1_PORT: 5432
      WORKER2_HOST: citus_worker2
      WORKER2_PORT: 5432
      WORKER3_HOST: citus_worker3
      WORKER3_PORT: 5432
      METABASE_DB_USER: "${METABASE_DB_USER}"
      METABASE_DB_PASSWORD: "${METABASE_DB_PASSWORD}"
      PROM_EXPORTER_DB_USER: "${PROM_EXPORTER_DB_USER}"
      PROM_EXPORTER_DB_PASSWORD: "${PROM_EXPORTER_DB_PASSWORD}"
      DATALOADER_DB_USER: "${DATALOADER_DB_USER}"
      DATALOADER_DB_PASSWORD: "${DATALOADER_DB_PASSWORD}"
      PGPOOL_DB_USER: "${PGPOOL_DB_USER}"
      PGPOOL_DB_PASSWORD: "${PGPOOL_DB_PASSWORD}"
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data
    depends_on:
      - citus_worker1
      - citus_worker2
      - citus_worker3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Init container (runs once, uses Postgres 17 client tools)
  citus_coordinator_init:
    image: postgres:17
    container_name: citus_coordinator_init
    env_file:
      - .env
    depends_on:
      citus_coordinator:
        condition: service_healthy
      citus_worker1:
        condition: service_healthy
      citus_worker2:
        condition: service_healthy
      citus_worker3:
        condition: service_healthy
    entrypoint: >
      bash -c "
      echo 'Waiting for coordinator...';
      until pg_isready -h citus_coordinator -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do
        sleep 2;
      done;

      echo 'Creating Citus extension on coordinator...';
      psql -h citus_coordinator -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"CREATE EXTENSION IF NOT EXISTS citus;\";

      echo 'Ensuring Citus extension on worker1...';
      psql -h citus_worker1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"CREATE EXTENSION IF NOT EXISTS citus;\";
      echo 'Ensuring Citus extension on worker2...';
      psql -h citus_worker2 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"CREATE EXTENSION IF NOT EXISTS citus;\";
      echo 'Ensuring Citus extension on worker3...';
      psql -h citus_worker3 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"CREATE EXTENSION IF NOT EXISTS citus;\";

      echo 'Registering workers with coordinator...';
      psql -h citus_coordinator -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<'EOSQL'
        SELECT master_add_node('citus_worker1', 5432);
        SELECT master_add_node('citus_worker2', 5432);
        SELECT master_add_node('citus_worker3', 5432);
      EOSQL

      echo 'Citus cluster initialization complete.'
      "
    environment:
      PGPASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend

  citus_worker1:
    env_file:
      - .env
    image: citusdata/citus:13.0.1
    container_name: citus_worker1
    hostname: citus-worker1
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data
    ports:
      - "${WORKER1_PORT}:5432"
    networks:
      - backend

  citus_worker2:
    env_file:
      - .env
    image: citusdata/citus:13.0.1
    container_name: citus_worker2
    hostname: citus-worker2
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
    ports:
      - "${WORKER2_PORT}:5432"
    networks:
      - backend

  citus_worker3:
    env_file:
      - .env
    image: citusdata/citus:13.0.1
    container_name: citus_worker3
    hostname: citus-worker3
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - citus_worker3_data:/var/lib/postgresql/data
    ports:
      - "${WORKER3_PORT}:5432"
    networks:
      - backend

  # -----------------------------
  # pgPool-II - connection pooling and failover (Bitnami)
  # -----------------------------
  pgpool:
    env_file:
      - .env
    image: "bitnami/pgpool:latest"
    container_name: pgpool
    environment:
      PGPOOL_BACKEND_NODES: "0:citus_coordinator:5432,1:citus_worker1:5432,2:citus_worker2:5432,3:citus_worker3:5432"
      PGPOOL_POSTGRES_USERNAME: "${POSTGRES_USER}"
      PGPOOL_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGPOOL_ADMIN_USERNAME: "${PGPOOL_ADMIN_USERNAME}"
      PGPOOL_ADMIN_PASSWORD: "${PGPOOL_ADMIN_PASSWORD}"
      PGPOOL_SR_CHECK_USER: "${PGPOOL_SR_CHECK_USER}"
      PGPOOL_SR_CHECK_PASSWORD: "${PGPOOL_SR_CHECK_PASSWORD}"
    ports:
      - "${PGPOOL_PORT}:5432"
    volumes:
      - ./db/pgpool:/opt/bitnami/pgpool/conf
    depends_on:
      - citus_coordinator
      - citus_worker1
      - citus_worker2
      - citus_worker3
    networks:
      - backend

  # rest of services unchanged...
  postgres_exporter:
    env_file:
      - .env
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${PROM_EXPORTER_DB_USER}:${PROM_EXPORTER_DB_PASSWORD}@citus_coordinator:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - citus_coordinator
    networks:
      - backend

  prometheus:
    env_file:
      - .env
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    networks:
      - backend

  grafana:
    env_file:
      - .env
    image: grafana/grafana:9.5.2
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    networks:
      - backend

  metabase:
    env_file:
      - .env
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "${POSTGRES_DB}"
      MB_DB_PORT: "5432"
      MB_DB_USER: "${METABASE_DB_USER}"
      MB_DB_PASS: "${METABASE_DB_PASSWORD}"
      MB_DB_HOST: "citus_coordinator"
      MB_SETUP_ADMIN_EMAIL: "${METABASE_ADMIN_EMAIL}"
      MB_SETUP_ADMIN_PASSWORD: "${METABASE_ADMIN_PASSWORD}"
    ports:
      - "${METABASE_PORT}:3000"
    depends_on:
      - citus_coordinator
    networks:
      - backend

  dataloader:
    env_file:
      - .env
    image: python:3.11-slim
    container_name: dataloader
    working_dir: /app
    volumes:
      - ./data:/data:ro
      - ./scripts/ingest_helper.py:/app/ingest_helper.py:ro
      - ./scripts/ingest_run.sh:/app/ingest_run.sh:ro
    entrypoint: ["/bin/bash","/app/ingest_run.sh"]
    environment:
      DATALOADER_DB_USER: "${DATALOADER_DB_USER}"
      DATALOADER_DB_PASSWORD: "${DATALOADER_DB_PASSWORD}"
      DATALOADER_DB_HOST: "citus_coordinator"
      DATALOADER_DB_PORT: "5432"
      DATALOADER_DB_NAME: "${POSTGRES_DB}"
    networks:
      - backend

networks:
  backend:

volumes:
  citus_coordinator_data:
  citus_worker1_data:
  citus_worker2_data:
  citus_worker3_data:
  prometheus_data:
  grafana_data: