# prometheus.yml - minimal, auto-scrapes Postgres exporter and node/cadvisor if added
global:
  scrape_interval: ${PROM_SCRAPE_INTERVAL}
  evaluation_interval: ${PROM_SCRAPE_INTERVAL}

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Add node_exporter / cadvisor scrape targets if you add them later